kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go mod download
  - go test
  - go vet
  - go build

- name: release
  image: golang
  commands:
  - git fetch --tags
  - go get github.com/mitchellh/gox
  - echo `make version`
  - make release
  when:
    event:
    - tag

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: drone_github_releases
    files: build/*
  when:
    event:
    - tag
